# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7dac9b353276f30fdcb19a3a1dfe86306f8098cb219e09e9ee91cbbadf8fa1699c589f6dbc793eb80cb079c6c0fbed7aa6db5d6071c1d7750214eb8bb6d64b

test:
  secret_key_base: 87ac991b7fc9096fb42758278665fc9861d85869ddcd0acf06c18a5ab84999f6c646d83d5f3fdfa47004b3bb699ba0ecfce275e871386c5d7d862a8b44e23b27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
